include:
  - path: ./mssql_en/compose.yaml
    env_file: ./mssql_en/.env
  - path: ./mssql_es/compose.yaml
    env_file: ./mssql_es/.env
  - path: ./postgresql/compose.yaml
    env_file: ./postgresql/.env
  - path: ./postgresql17/compose.yaml
    env_file: ./postgresql17/.env
  - path: ./mariadb/compose.yaml
    env_file: ./mariadb/.env
  - path: ./mysql/compose.yaml
    env_file: ./mysql/.env
  - path: ./mongodb/compose.yaml
    env_file: ./mongodb/.env
