include:
  - path: ./mssql2025/compose.yaml
    env_file: ./mssql2025/.env
  - path: ./postgresql18/compose.yaml
    env_file: ./postgresql18/.env
  - path: ./postgresql17/compose.yaml
    env_file: ./postgresql17/.env
  - path: ./mariadb/compose.yaml
    env_file: ./mariadb/.env
  - path: ./mysql/compose.yaml
    env_file: ./mysql/.env
  - path: ./mongodb/compose.yaml
    env_file: ./mongodb/.env
