[network]
tcpport = 1433
forceencryption = 1
tlscert = /etc/ssl/mssql/server-cert.pem
tlskey = /etc/ssl/mssql/server-key.pem

[memory]
memorylimitmb = 1500

[sqlagent]
enabled = true

[errorlog]
numfiles = 8

[filelocation]
defaultdatadir = /var/opt/mssql/data
defaultlogdir = /var/opt/mssql/log
defaultbackupdir = /var/opt/mssql/backup
errorlogfile = /var/opt/mssql/log/errorlog
masterdbdir = /var/opt/mssql/data
masterdblogdir = /var/opt/mssql/log

[telemetry]
customerfeedback = false
