services:

  mariadb:
    image: mariadb:11.4.10
    container_name: mariadb
    hostname: mariadb
    restart: no
    profiles:
      - mariadb
    ports:
      - "${BIND_ADDRESS}:3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_backup:/var/lib/mysql-backup
      - mariadb_log:/var/log/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: "1.5"
        reservations:
          memory: 256M
          cpus: "0.25"

volumes:
  mariadb_data:
  mariadb_backup:
  mariadb_log:
