services:

  mysql:
    image: mysql:8.4.8
    container_name: mysql8
    hostname: mysql8
    restart: no
    profiles:
      - mysql
    ports:
      - "${BIND_ADDRESS}:3306:3306"
    volumes:
      - mysql8_data:/var/lib/mysql
      - mysql8_backup:/var/lib/mysql-backup
      - mysql8_log:/var/log/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: "1.5"
        reservations:
          memory: 256M
          cpus: "0.25"

volumes:
  mysql8_data:
  mysql8_backup:
  mysql8_log:
