services:

  postgresql:
    image: postgres:18.2
    container_name: postgresql18
    hostname: postgresql18
    restart: no
    profiles:
      - postgresql18
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - "${BIND_ADDRESS}:5432:5432"
    volumes:
      - postgresql18_data:/var/lib/postgresql/data
      - postgresql18_backup:/var/lib/postgresql/backup
      - postgresql18_log:/var/log/postgresql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: "1.5"
        reservations:
          memory: 256M
          cpus: "0.25"

volumes:
  postgresql18_data:
  postgresql18_backup:
  postgresql18_log:
